name: Deploy

on:
  push:
    branches:
      - master
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: dev
      - name: Build
        run: flutter config --enable-web && flutter build web
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1.0.0
        with:
          name: site
          path: build/web
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: site
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v1.3.0
        with:
          args: deploy --only hosting:xmux-app
        env:
          PROJECT_ID: xmux-app
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
