name: Deploy

on:
  push:
    branches:
      - release

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - name: Build
        run: flutter build web --release --web-renderer html
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Website
          path: build/web
  DeployGithubStatic:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Website
          path: Website
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.DEPLOY_STATIC }}
          external_repository: XMUMY/static
          publish_branch: website
          publish_dir: ./Website
  DeployFirebase:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Website
          path: Website
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@v13.4.0
        with:
          args: deploy --only hosting:xmux-app
        env:
          PROJECT_ID: xmux-app
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
